server:
  port: 8084

spring:
  application:
    name: group-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/group_service
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # validate / update / create / create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
